### ISSUE TITLE
pathogen doesn't read in and process traditional YAML for input

### ISSUE THREAD

**Issue by chrisbsmith** [galaho/pathogen#59]
If I have a set of templates that define two people, `person1` and `person2`, it would be nice to be able to pass in a YAML file that has indention formatting.

For example, if my template looked like this:

```
team: {{ variable "team" }}
person1:
  name:  {{ variable "person1.name" }}
  email: {{ variable "person1.email" }}
  favorite drink: {{ variable "person1.drink" }}

person2:
  name:  {{ variable "person2.name" }}
  email: {{ variable "person2.email" }}
  favorite drink: {{ variable "person2.drink" }}
```

Then the input file may look something like this:

```
team: winners
person1:
  name: chris
  email: chris@job.com
  drink: bourbon
person2:
  name: josh
  email: josh@job.com
  drink: warm beer
```

Currently, this type of input file in not supported and pathogen will fail to use the inputs. 

Also of note, if this type of input is provided even with a valid `team` value, pathogen will still prompt for `team`.
